/**
 * "IntrusionAlert" Java class is free software: you can redistribute
 * it and/or modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version always keeping
 * the additional terms specified in this license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 *
 * Additional Terms of this License
 * --------------------------------
 *
 * 1. It is Required the preservation of specified reasonable legal notices
 *   and author attributions in that material and in the Appropriate Legal
 *   Notices displayed by works containing it.
 *
 * 2. It is limited the use for publicity purposes of names of licensors or
 *   authors of the material.
 *
 * 3. It is Required indemnification of licensors and authors of that material
 *   by anyone who conveys the material (or modified versions of it) with
 *   contractual assumptions of liability to the recipient, for any liability
 *   that these contractual assumptions directly impose on those licensors
 *   and authors.
 *
 * 4. It is Prohibited misrepresentation of the origin of that material, and it is
 *   required that modified versions of such material be marked in reasonable
 *   ways as different from the original version.
 *
 * 5. It is Declined to grant rights under trademark law for use of some trade
 *   names, trademarks, or service marks.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (lgpl.txt).  If not, see <http://www.gnu.org/licenses/>
 */

package recparser;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This class represents an intrusion alert generated by one of the sources of 
 * alerts.
 * 
 * @author UPM (member of RECLAMO Development Team)(http://reclamo.inf.um.es)
 * @version 1.0
 */
public class IntrusionAlert {
    private String _intCount; //required
    private String _intDetectionTime;//required <DetectTime> o <reclamo:Timestamp>
    private String _intAlertCreateTime; //required <CreateTime>
    private String _intAnalyzerTime; //<AnalyzerTime>
    private String _analyzerID; //required <Analyzer analyzerid>
    private String _intID; // required <Alert ident>
    private String _intType; //required <Classification text> o <CorrelationAlert><name> o <Assessment><Impact type>
    private int _intSeverity; //required <Impact severity>
    private int _intImpact; //required
    private double _analyzerconfidence; //required <reclamo:Trust>
    private double _realIntrusionImpact; //required
    private String _nextIntID;
    private String _intName;
    private String _intCompletion; //<Assessment completion>
    private ArrayList<IntrusionTarget> _intTarget; //OK: Asignacion
    private ArrayList<IntrusionSource> _intSource;
    private double _targetLevelOfImportance; //required
    private String _messageID;
    private String _description;
        
    public IntrusionAlert(){
        _intCount=null;        
        _intType=null;
        _intAlertCreateTime=null;
        _intAnalyzerTime=null;
        _analyzerID=null;
        _intID=null;
        _intDetectionTime=null;
        _intSeverity=-1;
        _intImpact=-1;
        _analyzerconfidence=-1.0;
        _realIntrusionImpact=0.0;
        _nextIntID=null;
        _intName=null;
        _intCompletion=null;
        _intTarget = new ArrayList<IntrusionTarget>();
        _intSource = new ArrayList<IntrusionSource>();
        _targetLevelOfImportance=0.0;
        _messageID=null;
        _description=null;
      }
    
    public IntrusionAlert(String intCount, String intDetectionTime, String intAlertCreateTime, String IDSID, String intID, String intType, int severity, int intImpact, double confidence, String nextIntID){
        _intCount=intCount;        
        _intType=intType;
        _intAlertCreateTime=intAlertCreateTime;
	_intAnalyzerTime=null;
	_intDetectionTime=intDetectionTime;
        _analyzerID=IDSID;
        _intID= intID;
        _analyzerconfidence=confidence;
        _intTarget = new ArrayList<IntrusionTarget>();
        _intSource = new ArrayList<IntrusionSource>();
        _intSeverity= severity;

	//Sin valores iniciales
	_intImpact=intImpact;
	_realIntrusionImpact=0.0;
	_nextIntID=null;
	_intName=null;
	_intCompletion=null;
	_targetLevelOfImportance=0.0;
	_messageID=null;
	_description=null;
    }
    
    public String getIntCount(){
        return _intCount;
    }     
    
    public String getIntType(){
        return _intType;
    }
    
    public String getIntAlertCreateTime(){
        return _intAlertCreateTime;
    }

    public String getIntAnalyzerTime(){
        return _intAnalyzerTime;
    }
    
    public String getAnalyzerID(){
        return _analyzerID;
    }    
   
    public String getIntID(){
        return _intID;
    } 
    
    public String getIntDetectionTime(){
        return _intDetectionTime;
    }
    
    public ArrayList<IntrusionTarget> getIntrusionTarget(){
        return _intTarget;
    }    
       
    public int getIntSeverity(){
        return _intSeverity;
    }    
    
    public int getIntImpact(){
        return _intImpact;
    }    
    
    public double getRealIntImpact(){
        return _realIntrusionImpact;
    }

    public double getAnalyzerConfidence(){
        return _analyzerconfidence;
    }    
    
    public String getNextIntID(){
        return _nextIntID;
    }
    
    public String getIntName(){
        return _intName;
    } 
    
    public String getIntCompletion(){
        return _intCompletion;
    }
        
    public ArrayList<IntrusionSource> getIntrusionSource(){
        return _intSource;
    }

    public double getTargetLOI(){
        return _targetLevelOfImportance;
    }
    
    public String getMessageID(){
        return _messageID;
    }
    
    public String getDescription(){
        return _description;
    }

        
    public void setIntCount(String value){
        _intCount = value;
    } 
    
    public void setIntType(String value){
        _intType = value;
    }   
    
    public void setIntAlertCreateTime(String value){
        _intAlertCreateTime = value;
    }

    public void setIntAnalyzerTime(String value){
        _intAnalyzerTime = value;
    }
    
    public void setAnalyzerID(String value){
        _analyzerID = value;
    }    
    
    public void setIntID(String value){
        _intID = value;
    } 
    
    public void setIntDetectionTime(String value){
        _intDetectionTime = value;
    }
        
    public void setIntrusionTarget(IntrusionTarget value){
        _intTarget.add(value);
    }
    
    public void setIntSeverity(int value){
        _intSeverity = value;
    }    
    
    public void setIntImpact(int value){
        _intImpact = value;
    }    

    public void setRealIntImpact(double value){
        _realIntrusionImpact=value;
    }

    public void setAnalyzerConfidence(double value){
        _analyzerconfidence = value;
    }    
    
    public void setNextIntID(String value){
        _nextIntID = value;
    }    
    
    public void setIntName(String value){
        _intName = value;
    }

    public void setIntCompletion(String value){
        _intCompletion = value;
    }
    
    public void setIntrusionSource(IntrusionSource value){
        _intSource.add(value);
    }

    public void setTargetLOI(double value){
        _targetLevelOfImportance =value;
    }

    public void setMessageID(String value){
        _messageID=value;
    }

    public void setDescription(String value){
        _description=value;
    }
    
    public void printAlert(){
        System.out.println("********************ALERTA*************************");
        System.out.println("IntrusionType: "+getIntType()+ " ; intrusionName: "+ getIntName()+" ; nextIntrusionID: "+getNextIntID()+ " ; intrusionAlertCreateTime: "+getIntAlertCreateTime()+
                " ; intrusionImpact: "+ Integer.toString(getIntImpact())+ " ; intrusionCount: "+ getIntCount()+ " ; IDSconfidence: "+Double.toString(getAnalyzerConfidence())+ " ; intrusionID: "+
                getIntID() + " ; intrusionDetectionTime: "+ getIntDetectionTime() + " ; intrusionSeverity: "+ Integer.toString(getIntSeverity()));
        
        System.out.println("TARGET(s):");
        Iterator it =getIntrusionTarget().iterator();
        while(it.hasNext()){
            IntrusionTarget intru = (IntrusionTarget)it.next();
            List<Address> addressList=intru.getAddress();
            Iterator addressit = addressList.iterator();
            while(addressit.hasNext()){
                Address address=(Address)addressit.next();
                String addressIP = address.getAddress();
                int port = intru.getServicePort();
                System.out.println("TargetIP: "+addressIP+" ; targetServicePort: "+port);
            }            
        }
        
        System.out.println("SOURCE(s):");
        Iterator itS =getIntrusionSource().iterator();
        while(itS.hasNext()){
            IntrusionSource intruSource = (IntrusionSource)itS.next();
            List <Address> addressList=intruSource.getNode();
            Iterator addressit = addressList.iterator();
            while(addressit.hasNext()){
                Address address=(Address)addressit.next();
                String addressIP = address.getAddress();
                int port = intruSource.getPortSrc();
                System.out.println("SourceIP: "+addressIP+" ; sourcePort: "+port);
            }        
            
        }
               
    }
    
    public boolean isEmpty(){
        if (getIntCount()==null && getIntDetectionTime()==null && getIntAlertCreateTime()==null 
                && getAnalyzerID()==null && getIntID()==null && getIntType()==null && getIntSeverity()==-1
                && getIntImpact()==-1 && getAnalyzerConfidence()==-1.0 && getIntrusionTarget() == null
                && getIntrusionSource() == null && getNextIntID()==null
                && getIntName()==null){
            return true;
        }
        else{
            return false;
        }
    
    }
    
    public boolean validate(){
        System.out.println(getIntCount());
        System.out.println(getIntAlertCreateTime());
        System.out.println(getIntDetectionTime());
        System.out.println(getAnalyzerID());
        System.out.println(getIntID());
        System.out.println(getIntType());
        System.out.println(getAnalyzerConfidence());
        System.out.println(getIntSeverity());
        System.out.println(getIntrusionTarget());
        System.out.println(getIntName());
        
        /*Necesario para la integración de Murcia*/
        if (getIntCount()!=null && getIntAlertCreateTime()!=null && getIntDetectionTime()!=null && getAnalyzerID()!=null && getIntID()!=null
                && getIntType()!=null && getAnalyzerConfidence()>=0.0 && getIntSeverity()>-1 &&
                !(getIntrusionTarget().isEmpty()) && getIntName()!=null){
            return true;
        }
        else{
            return false;
        }
    }      
}
