#!/usr/bin/perl -w

# Author: Shagin Enose
# Date: 18-Dec-2010
# Type: Naigos Plugin
# Description: Checks ssh failed login attempts


use strict;
use English;
use Getopt::Long;
use File::stat;
use vars qw($PROGNAME);
use lib "/usr/lib/nagios/plugins";
use utils qw (%ERRORS &print_revision &support);

sub print_help ();
sub print_usage ();

my ($opt_c, $opt_w, $opt_h, $opt_V);
my ($result, $message);
my $failurecount;
my $position;
$PROGNAME="check_ssh_faillogin";

$opt_w = 5;
$opt_c = 10;

Getopt::Long::Configure('bundling');
GetOptions(
	"V"   => \$opt_V, "version"	=> \$opt_V,
	"h"   => \$opt_h, "help"	=> \$opt_h,
	"w=i" => \$opt_w, "warning=i" => \$opt_w,
	"c=i" => \$opt_c, "critical=i" => \$opt_c);

if ($opt_V) {
	print_revision($PROGNAME, '@NP_VERSION@');
	exit $ERRORS{'OK'};
}

if ($opt_h) 
{
	print_help();
	exit $ERRORS{'OK'};
}

$result = 'OK';

$failurecount =0;
$position=0;
my $statfile ='/etc/nagios/check_ssh_faillogin.dat';
if(-e $statfile)
 {
        open(STAT_HAND, "<$statfile") or die "an error occured: $!";
        while(<STAT_HAND>)
        {
                $position = $_;
        }
        close(STAT_HAND);
 }
#open (FILEHANDLE, "</var/log/secure") or die "an error occured: $!";
open (FILEHANDLE, "</var/log/auth.log") or die "an error occured: $!";
seek FILEHANDLE,$position , 0;
while(<FILEHANDLE>)
{
        if(index($_,"Failed password for",0)!=-1)
        {
                $failurecount++;
        }
$position = tell FILEHANDLE;
}
close(FILEHANDLE) or die "an error occured while trying to close the file: $!";

open(STAT_HAND, "+>$statfile") or die "an error occured: $!";
print STAT_HAND "$position";
close(STAT_HAND);

if ($failurecount > $opt_c)  
{
	$result = 'CRITICAL';
}
elsif ($failurecount > $opt_w) 
{
	$result = 'WARNING';
}

print "LOGIN ATTEMPTS $result: $failurecount failure login attempts\n";
exit $ERRORS{$result};

sub print_usage () {
	print "Usage:\n";
	print "  $PROGNAME [-w <count>] [-c <count>] \n";
	print "  $PROGNAME [-h | --help]\n";
	print "  $PROGNAME [-V | --version]\n";
}

sub print_help () {
	print_revision($PROGNAME, '@NP_VERSION@');
	print "Copyright (c) 2010 Shagin Enose\n\n";
	print_usage();
	print "\n";
	print "  <count>  count must be a positive number(default: warn 5, crit 10)\n";
	print "\n";
	support();
}

