/**
 * "IntrusionAlert" Java class is free software: you can redistribute
 * it and/or modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version always keeping
 * the additional terms specified in this license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 *
 * Additional Terms of this License
 * --------------------------------
 *
 * 1. It is Required the preservation of specified reasonable legal notices
 *   and author attributions in that material and in the Appropriate Legal
 *   Notices displayed by works containing it.
 *
 * 2. It is limited the use for publicity purposes of names of licensors or
 *   authors of the material.
 *
 * 3. It is Required indemnification of licensors and authors of that material
 *   by anyone who conveys the material (or modified versions of it) with
 *   contractual assumptions of liability to the recipient, for any liability
 *   that these contractual assumptions directly impose on those licensors
 *   and authors.
 *
 * 4. It is Prohibited misrepresentation of the origin of that material, and it is
 *   required that modified versions of such material be marked in reasonable
 *   ways as different from the original version.
 *
 * 5. It is Declined to grant rights under trademark law for use of some trade
 *   names, trademarks, or service marks.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (lgpl.txt).  If not, see <http://www.gnu.org/licenses/>
 */

package parser;

import java.util.ArrayList;

/**
 * This class represents an intrusion alert generated by one of the sources of 
 * alerts.
 * 
 * @author UPM (member of RECLAMO Development Team)(http://reclamo.inf.um.es)
 * @version 1.0
 */
public class IntrusionAlert2 {
    private String _intCount;
    private String _intDetectionTime; // <DetectTime> o <reclamo:Timestamp>
    private String _intAlertCreateTime; //<CreateTime>
    private String _analyzerID; //<Analyzer analyzerid>
    private String _intID; // <Alert messageid>
    private String _intType; //<Classification text> o <CorrelationAlert><name>
    private int _intSeverity; //<Impact severity>
    private int _intImpact; 
    private String _analyzerconfidence; //<reclamo:Trust>
    //private String _attackerLocation; //<Source><Node><Location>
    //private String _sourceIP; //<Source><Node><Address><address>
    //private String _sourceName; //<Source><Node><name>
    private int _portDest; //Duplico la info del puerto destino?
    //private int _portSrc; //<Source><Service><port>
    private String _nextIntID;
    private String _intName;
    private String _intCompletion; //<Assessment completion>
    //private String _intSpoofed; //<Source spoofed>
    private IntrusionTarget _intTarget; //OK: Asignación
    private IntrusionSource _intSource;
    private String _targetIntDecoy; //¿?
    //private String _protocol;   //<Source><Service><protocol>


    
    public IntrusionAlert2(){
        _intCount=null;
        _intDetectionTime=null;
        _intAlertCreateTime=null;
        _analyzerID=null;
        _intID=null;
        _intType=null;
        _intSeverity=-1;
        _intImpact=-1;
        _analyzerconfidence=null;
        /*_attackerLocation=null;
        _sourceIP=null;
        _sourceName=null;*/
        _portDest=-1;
        //_portSrc=-1;
        _nextIntID=null;
        _intName=null;
        _intCompletion=null;
        //_intSpoofed=null;
        _intTarget = null;
        _targetIntDecoy = null;
        _intSource = null;
        //_protocol = null;
    }
    
    public IntrusionAlert2(String intCount, String intDetectionTime, String intAlertCreateTime,
            String IDSID, String destIP, String intID, String intType, int intSeverity, int intImpact, String IDSconfidence,
            String attackerLocation, String sourceIP, int portDest, int portSrc, String nextIntID, String protocol){
        _intCount=intCount;
        _intDetectionTime=intDetectionTime;
        _intAlertCreateTime=intAlertCreateTime;
        _analyzerID=IDSID;
        //_destIP=destIP;
        _intID=intID;
        _intType=intType;
        _intSeverity=intSeverity;
        _intImpact=intImpact;
        _analyzerconfidence=IDSconfidence;
        /*_attackerLocation=attackerLocation;
        _sourceIP=sourceIP;*/
        _portDest=portDest;
        //_portSrc=portSrc;
        _nextIntID=nextIntID;
        //_protocol=protocol;
    }
    
    public String getIntCount(){
        return _intCount;
    } 
    
    public String getIntDetectionTime(){
        return _intDetectionTime;
    }
    
    public String getIntAlertCreateTime(){
        return _intAlertCreateTime;
    }    
    
    public String getAnalyzerID(){
        return _analyzerID;
    }    
    
    public IntrusionTarget getIntrusionTarget(){
        return _intTarget;
    }    
    
    
    public IntrusionSource getIntrusionSource(){
        return _intSource;
    }  
    
    public String getIntID(){
        return _intID;
    }    
    
    public String getIntType(){
        return _intType;
    }    
    
    public int getIntSeverity(){
        return _intSeverity;
    }    
    
    public int getIntImpact(){
        return _intImpact;
    }    
    
    public String getAnalyzerConfidence(){
        return _analyzerconfidence;
    }    
    
   /* public String getAttackerLocation(){
        return _attackerLocation;
    }    
    
    public String getSourceIP(){
        return _sourceIP;
    }    
    
    public String getSourceName(){
        return _sourceName;
    }*/
    
    public int getPortDest(){
        return _portDest;
    }    
    
   /* public int getPortSrc(){
        return _portSrc;
    }*/
    
    public String getNextIntID(){
        return _nextIntID;
    }
    
    public String getIntName(){
        return _intName;
    } 
    
    public String getIntCompletion(){
        return _intCompletion;
    }
    
   /* public String getIntSpoofed(){
        return _intSpoofed;
    }*/
    
    public String getTargetIntDecoy(){
        return _targetIntDecoy;
    }
    
   /* public String getProtocol(){
        return _protocol;
    }*/
    
    public void setIntCount(String value){
        _intCount = value;
    } 
    
    public void setIntDetectionTime(String value){
        _intDetectionTime = value;
    }
    
    public void setIntAlertCreateTime(String value){
        _intAlertCreateTime = value;
    }    
    
    public void setAnalyzerID(String value){
        _analyzerID = value;
    }    
    
    public void setIntrusionTarget(IntrusionTarget value){
        _intTarget = value;
    }    
    
    public void setIntrusionSource(IntrusionSource value){
        _intSource = value;
    }    
    
    public void setIntID(String value){
        _intID = value;
    }    
    
    public void setIntType(String value){
        _intType = value;
    }    
    
    public void setIntSeverity(int value){
        _intSeverity = value;
    }    
    
    public void setIntImpact(int value){
        _intImpact = value;
    }    
    
    public void setAnalyzerConfidence(String value){
        _analyzerconfidence = value;
    }    
    
   /* public void setAttackerLocation(String value){
        _attackerLocation = value;
    }    
    
    public void setSourceIP(String value){
        _sourceIP = value;
    }    
    
    public void setSourceName(String value){
        _sourceName = value;
    }*/    
    
    public void setPortDest(int value){
        _portDest = value;
    }    
    
    /*public void setPortSrc(int value){
        _portSrc = value;
    }
    */
    public void setNextIntID(String value){
        _nextIntID = value;
    }    
    
    public void setIntName(String value){
        _intName = value;
    }
    
    public void setIntCompletion(String value){
        _intCompletion = value;
    }
    
    /*public void setIntSpoofed(String value){
        _intSpoofed = value;
    }*/
    
    public void setTargetIntDecoy(String value){
        _targetIntDecoy = value;
    }
    
   /* public void setProtocol(String value){
        _protocol = value;
    }*/
    
   /* public void printAlert(){
        System.out.println("********************ALERTA*************************");
        System.out.println("AttackerLocation: "+getAttackerLocation()+ "; intrusionType: "+getIntType()+ " ; intrusionName: "+ getIntName()+" ; nextIntrusionID: "+getNextIntID()+ " ; intrusionAlertCreateTime: "+getIntAlertCreateTime()+
                " ; targetOfIntrusionID: "+getIntrusionTarget().getAddressIP()+ " ; intrusionImpact: "+ Integer.toString(getIntImpact())+ " ; portDest: "+
                Integer.toString(getPortDest())+ " ; portSrc: "+Integer.toString(getPortSrc())+ " ; intrusionCount: "+ getIntCount()+ " ; IDSconfidence: "+getAnalyzerConfidence()+ " ; intrusionID: "+
                getIntID() + " ; intrusionDetectionTime: "+ getIntDetectionTime() + " ; intrusionSeverity: "+ Integer.toString(getIntSeverity())+
                " ; sourceOfIntrusionID: " + getSourceIP()+" ; protocol: "+getProtocol());
    }
    
    public boolean isEmpty(){
        if (getIntCount()==null && getIntDetectionTime()==null && getIntAlertCreateTime()==null && getAnalyzerID()==null && getIntrusionTarget()==null
                && getIntID()==null && getIntType()==null && getIntSeverity()==-1 && getIntImpact()==-1 && getAnalyzerConfidence()==null && getAttackerLocation()==null && getSourceIP()==null 
                && getPortDest() == -1 && getPortSrc() == -1 && getNextIntID()==null && getIntName()==null){
            return true;
        }
        else{
            return false;
        }
    
    }
    
    public boolean validate(){
        String ipaddr = null;
        if(getIntrusionTarget()!=null){
            ipaddr= getIntrusionTarget().getAddressIP();
        }
        if (getIntCount()!=null &&  getIntDetectionTime()!=null && getIntAlertCreateTime()!=null && getAnalyzerID()!=null && ipaddr!=null
                && getIntID()!=null && getIntType()!=null && getIntSeverity() >=0 && getIntImpact()>=0 && getAnalyzerConfidence()!=null && getAttackerLocation()!=null && getSourceIP()!=null){
            return true;
        }
        else{
            return false;
        }
    }   */ 
    
}